[package]
name = "replicative"
version = "0.1.0"
authors = ["Izzy Swart <zenerboson@gmail.com>"]
edition = "2018"

[dependencies]
futures-preview = { version = "=0.3.0-alpha.19", features = ["async-await"] }
void = "1.0.2"
failure = "0.1.6"
